steps:
  # Build and deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'snake-game', 
          '--image', 'gcr.io/$PROJECT_ID/snake-game', 
          '--platform', 'managed',
          '--region', 'us-central1',
          '--allow-unauthenticated',
          '--source', '.']

options:
  logging: CLOUD_LOGGING_ONLY
