steps:
  # Build and tag the image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/snake-repo/snake-game:latest',
      '.'
    ]
  
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/snake-repo/snake-game:latest'
    ]
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'snake-game'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/snake-repo/snake-game:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=3000'

options:
  logging: CLOUD_LOGGING_ONLY
